# theme: jekyll-theme-hacker
theme: jekyll-theme-cayman
title: The Procrastinators
description: Group 26's website for CSE 110. We might change the name if we have time

#Show link to repo
# github:
#     is_project_page: true
kramdown:
    auto_ids: true