# theme: jekyll-theme-hacker
# theme: jekyll-theme-cayman
title: The Procrastinators
description: Group 26's website for CSE 110.

#Show link to repo
# github:
#     is_project_page: true
kramdown:
  auto_ids: true
exclude:
  [
    cypress,
    coverage,
    node_modules,
    cypress.json,
    Gemfile,
    Gemfile.lock,
    package-lock.json,
    package.json,
    JSDocTemplate,
  ]
